// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Kómma",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Kómma",
            targets: ["AppModule"],
            bundleIdentifier: "com.thomasconchon.SSC-26",
            teamIdentifier: "66DL9V5NKK",
            displayVersion: "0.5",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .mic),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/simibac/ConfettiSwiftUI", "2.0.3"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "ConfettiSwiftUI", package: "confettiswiftui")
            ],
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)